apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_NAME: "postgres"
  DB_HOST: "postgresql-service.default.svc.cluster.local"
  DB_USER: "admin"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  DB_PASSWORD: R2FxZlhUUUpqRENiZmlSRw==
